name: flutter_yt_dlp_example
description: "Demonstrates how to use the flutter_yt_dlp plugin."
publish_to: 'none'

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_yt_dlp:
    path: ../
  cupertino_icons: ^1.0.8
  permission_handler: ^11.4.0
  logging: ^1.2.0
  path_provider: ^2.1.4
  provider: ^6.1.2

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true